### ISSUE TITLE
Problems making design changes if no operational internet connection; documentation does not note requirement for internet connection.

### ISSUE THREAD

**Issue by selebi-pikwe** [msawczyn/EFDesigner2022#96]
If there is no current internet connection:-
- the designer does not load the model fully/correctly (no properties page is displayed for the model);
- entities cannot be added; entity properties cannot be changed ('The given key was not present in the dictionary' error);
- produces build error (see below).

Strangely, Enum addition/changing seems to work.

When the internet connection is restored, everything works fine again (but only after reloading VS, reloading the solution/projects and the EF model).

VS2022 17.8.7, EFDesigner 4.2.7.3, no changes to .tt files.

Build Error:
Running transformation: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Sawczyn.EFDesigner.EFModel.ModelRoot.get_NugetVersions() in D:\Code\EFDesigner2022\src\Dsl\CustomCode\Partials\ModelRoot.cs:line 529
   at Sawczyn.EFDesigner.EFModel.ModelRoot.GetEntityFrameworkPackageVersionNum() in D:\Code\EFDesigner2022\src\Dsl\CustomCode\Partials\ModelRoot.cs:line 510
   at Microsoft.VisualStudio.TextTemplating8B467D06333785AE07823DBF4F53B1DDAEE55C6880751ADE92C4E58D65EFF53E8D97A6019658EC8BDEDE7BA40E6AFE1E876482B38B24561B44B76237BDBA8E74.GeneratedTextTransformation.TransformText() in \Documents\GitRepos\LabSys15\LabSys15_Db_Lib\LabSys15_Db.tt:line 49		D: Code\EFDesigner2022\src\Dsl\CustomCode\Partials\ModelRoot.cs	529

**Comment by Er1c-C** [comment]
The same thing is happening to me, there is no way to solve it without connecting to the internet?
